/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varun Kalra
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        well.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pwd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        lbp1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        books = new javax.swing.JTable();
        jButton23 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        lbp2 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        f1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        jButton31 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        lbp4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        issuedbooks = new javax.swing.JTable();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        lbp3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tt1 = new javax.swing.JTextField();
        tt2 = new javax.swing.JTextField();
        tt3 = new javax.swing.JTextField();
        tt4 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        lbp5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ff1 = new javax.swing.JTextField();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        p4 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        well = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        adp1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LIBRARIANS = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        adp2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        adp3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 324, -1));

        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        p1.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 20));

        jLabel2.setText("Enter password here");
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 24, 200, 40));

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jButton3.setText("quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        p1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel27.setText("password = 1234");
        p1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 110, 100, -1));

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("VIEW BOOKS");

        books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Author Name", "Genre", "Name", "BookID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(books);

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton23.setText("show");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton30.setText("BACK");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbp1Layout = new javax.swing.GroupLayout(lbp1);
        lbp1.setLayout(lbp1Layout);
        lbp1Layout.setHorizontalGroup(
            lbp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbp1Layout.createSequentialGroup()
                .addGroup(lbp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbp1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(lbp1Layout.createSequentialGroup()
                        .addGroup(lbp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbp1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel8))
                            .addGroup(lbp1Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jButton23)))
                        .addGap(0, 146, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(lbp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbp1Layout.setVerticalGroup(
            lbp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbp1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton30)
                .addContainerGap())
        );

        getContentPane().add(lbp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton24.setText("ADD BOOK");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jLabel1.setText("BOOK NAME");

        jLabel15.setText("AUTHOR NAME");

        jLabel16.setText("GENRE");

        jLabel17.setText("BOOK CODE");

        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });

        jButton31.setText("BACK");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("ADD A BOOK");

        javax.swing.GroupLayout lbp2Layout = new javax.swing.GroupLayout(lbp2);
        lbp2.setLayout(lbp2Layout);
        lbp2Layout.setHorizontalGroup(
            lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbp2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(f3)
                    .addComponent(f2)
                    .addComponent(f1))
                .addGap(96, 96, 96))
            .addGroup(lbp2Layout.createSequentialGroup()
                .addGroup(lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbp2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButton24))
                    .addGroup(lbp2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton31))
                    .addGroup(lbp2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbp2Layout.setVerticalGroup(
            lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbp2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel26)
                .addGap(26, 26, 26)
                .addGroup(lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton24)
                .addGap(30, 30, 30)
                .addComponent(jButton31)
                .addContainerGap())
        );

        getContentPane().add(lbp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        issuedbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book Code", "Author Name", "Reader", "Contact_no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(issuedbooks);

        jButton26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton26.setText("SHOW");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("Back");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbp4Layout = new javax.swing.GroupLayout(lbp4);
        lbp4.setLayout(lbp4Layout);
        lbp4Layout.setHorizontalGroup(
            lbp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbp4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(lbp4Layout.createSequentialGroup()
                .addGroup(lbp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbp4Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton26))
                    .addGroup(lbp4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton27)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbp4Layout.setVerticalGroup(
            lbp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbp4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton27)
                .addGap(21, 21, 21))
        );

        getContentPane().add(lbp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel18.setText("Book Code");

        jLabel19.setText("Author");

        jLabel20.setText("Reader");

        jLabel21.setText("contact_No");

        tt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt2ActionPerformed(evt);
            }
        });

        tt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt3ActionPerformed(evt);
            }
        });

        jButton25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton25.setText("CONFIRM");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("News706 BT", 1, 18)); // NOI18N
        jLabel23.setText("Issue a Book");

        jButton32.setText("BACK");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbp3Layout = new javax.swing.GroupLayout(lbp3);
        lbp3.setLayout(lbp3Layout);
        lbp3Layout.setHorizontalGroup(
            lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbp3Layout.createSequentialGroup()
                .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbp3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbp3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(85, 85, 85)
                                .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbp3Layout.createSequentialGroup()
                                .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbp3Layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addGap(103, 103, 103))
                                        .addGroup(lbp3Layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addGap(101, 101, 101)))
                                    .addGroup(lbp3Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(81, 81, 81)))
                                .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tt2)
                                    .addComponent(tt3)
                                    .addComponent(tt4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))))
                    .addGroup(lbp3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jButton25)))
                    .addGroup(lbp3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton32)))
                .addGap(87, 87, 87))
        );
        lbp3Layout.setVerticalGroup(
            lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbp3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel23)
                .addGap(43, 43, 43)
                .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbp3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18))
                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(lbp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(lbp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Return an issued book");

        jLabel25.setText("Enter book code here");

        jButton28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton28.setText("CONFIRM");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setText("BACK");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbp5Layout = new javax.swing.GroupLayout(lbp5);
        lbp5.setLayout(lbp5Layout);
        lbp5Layout.setHorizontalGroup(
            lbp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbp5Layout.createSequentialGroup()
                .addGroup(lbp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(lbp5Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(jLabel24))
                        .addGroup(lbp5Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ff1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lbp5Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton28))
                    .addGroup(lbp5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton29)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        lbp5Layout.setVerticalGroup(
            lbp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbp5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel24)
                .addGap(55, 55, 55)
                .addGroup(lbp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton28)
                .addGap(18, 18, 18)
                .addComponent(jButton29)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(lbp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setText("Add Book");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        p4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 40, 80, -1));

        jButton15.setText("View Book");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        p4.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 40, 120, -1));

        jButton16.setText("Issue Book");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        p4.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jButton17.setText("View Issued Books");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        p4.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jButton18.setText("Return  Book");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        p4.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 180, 100, -1));

        jButton19.setText("Logout");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        p4.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 330, 420));

        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("LOGIN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        p2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jButton12.setText("BACK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        p2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        p2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 73, 77, -1));
        p2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 158, 77, -1));

        jLabel3.setText("ENTER YOUR USER ID");
        p2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 76, -1, -1));

        jLabel4.setText("ENTER PASSWORD HERE");
        p2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 161, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("LIBRARIAN WINDOW");
        p2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 210, 30));

        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 382, 326));

        well.setBackground(new java.awt.Color(204, 255, 204));
        well.setLayout(null);

        jButton10.setBackground(new java.awt.Color(204, 204, 255));
        jButton10.setText("ADMIN");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        well.add(jButton10);
        jButton10.setBounds(130, 90, 65, 23);

        jButton22.setText("LIBRARIAN");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        well.add(jButton22);
        jButton22.setBounds(120, 160, 87, 23);

        jLabel22.setFont(new java.awt.Font("Freehand521 BT", 1, 18)); // NOI18N
        jLabel22.setText("Login as -");
        well.add(jLabel22);
        jLabel22.setBounds(20, 20, 170, 30);

        getContentPane().add(well, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 303, 303));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("View librarians");

        LIBRARIANS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NAME", "CONTACT NUMBER", "CITY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LIBRARIANS);

        jButton9.setText("BACK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton21.setText("SHOW");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adp1Layout = new javax.swing.GroupLayout(adp1);
        adp1.setLayout(adp1Layout);
        adp1Layout.setHorizontalGroup(
            adp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adp1Layout.createSequentialGroup()
                .addGroup(adp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adp1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adp1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton9))
                    .addGroup(adp1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton21)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adp1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(112, 112, 112))
        );
        adp1Layout.setVerticalGroup(
            adp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adp1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(49, 49, 49))
        );

        getContentPane().add(adp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Add librarian");

        jLabel9.setText("Enter your city here");

        jLabel10.setText("Enter your contact no. here ");

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("CONFIRM");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Enter name here");

        jLabel12.setText("ASSIGN A LIBRARIAN ID ");

        jButton13.setText("BACK");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adp2Layout = new javax.swing.GroupLayout(adp2);
        adp2.setLayout(adp2Layout);
        adp2Layout.setHorizontalGroup(
            adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adp2Layout.createSequentialGroup()
                .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adp2Layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jLabel7))
                        .addGroup(adp2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addGap(90, 90, 90)
                            .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(t1)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adp2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adp2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(49, 49, 49))
                                .addGroup(adp2Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(65, 65, 65)))
                            .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(t3))))
                    .addGroup(adp2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton11))
                    .addGroup(adp2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton13)))
                .addGap(29, 29, 29))
        );
        adp2Layout.setVerticalGroup(
            adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adp2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adp2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(adp2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(adp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addContainerGap())
        );

        getContentPane().add(adp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("REMOVE LIBRARIANS");

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton20.setText("REMOVE LIBRARIAN");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel14.setText("ENTER LIBRARIAN ID HERE ");

        jButton33.setText("BACK");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adp3Layout = new javax.swing.GroupLayout(adp3);
        adp3.setLayout(adp3Layout);
        adp3Layout.setHorizontalGroup(
            adp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adp3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addGap(34, 34, 34)
                .addComponent(tf1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(adp3Layout.createSequentialGroup()
                .addGroup(adp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adp3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel13))
                    .addGroup(adp3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton20))
                    .addGroup(adp3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton33)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adp3Layout.setVerticalGroup(
            adp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adp3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel13)
                .addGap(39, 39, 39)
                .addGroup(adp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton20)
                .addGap(38, 38, 38)
                .addComponent(jButton33)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(adp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton4.setText("VIEW LIBRARIAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("ADD A LIBRARIAN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("REMOVE LIBRARIAN");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("LOG-OUT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton8)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton4)
                .addGap(42, 42, 42)
                .addComponent(jButton6)
                .addGap(39, 39, 39)
                .addComponent(jButton7)
                .addGap(36, 36, 36)
                .addComponent(jButton8)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
 well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(true);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
 well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(true);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        well.setVisible(false);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);     }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int pass=Integer.parseInt(pwd.getText());
      if(pass==1234){ 
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false); }
      else{JOptionPane.showMessageDialog(null,"WRONG PASSWORD TRY AGAIN");}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(true);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(true);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);     }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(true);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(true);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
 well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(true);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
 well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
int I = Integer.parseInt(tf1.getText());
try{
        Class.forName("java.sql.Driver");
       Connection co= DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
        java.sql.Statement stmt = co.createStatement();
        String q ="Delete from librarian where ID="+I+"";
        stmt.executeUpdate(q);
       JOptionPane.showMessageDialog(null,"Data removed successfully");
            }
    catch(Exception e){JOptionPane.showMessageDialog(null,e);}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
DefaultTableModel model =(DefaultTableModel) LIBRARIANS.getModel();   
int row=model.getRowCount();
if(row>0){
    for(int i=0;i<row;i++)
    {model.removeRow(0);}
    try{
        Class.forName("java.sql.Driver");
       Connection co= DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
        java.sql.Statement stmt = co.createStatement();
        String q ="select * from librarian";
        ResultSet rs =stmt.executeQuery(q);
        while(rs.next()){
        String n = rs.getString("Name");
        int cn = rs.getInt("Contact_no");
        String c = rs.getString("city");
        int ID =rs.getInt("ID");
        model.addRow(new Object[] {n,cn,c,ID});
        }
       rs.close();
       stmt.close();
       co.close();
            }
    catch(Exception e){JOptionPane.showMessageDialog(null,e);}
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
String name=t1.getText();
String city=t2.getText();
int contact_no=Integer.parseInt(t3.getText());
int ID=Integer.parseInt(t4.getText());
try{
        Class.forName("java.sql.Driver");
       Connection co= DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
        java.sql.Statement stmt = co.createStatement();
        String q ="insert into librarian values('"+name+"',"+contact_no+",'"+city+"',"+ID+")";
        stmt.executeUpdate(q);
       JOptionPane.showMessageDialog(null,"Data added successfully");
            }
    catch(Exception e){JOptionPane.showMessageDialog(null,e);}
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
DefaultTableModel mode =(DefaultTableModel) books.getModel();   
int row=mode.getRowCount();
if(row>0){
    for(int i=0;i<row;i++)
    {mode.removeRow(0);}
    try{
        Class.forName("java.sql.Driver");
       Connection co= DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
        java.sql.Statement stmt = co.createStatement();
        String q ="select * from books";
        ResultSet rs =stmt.executeQuery(q);
        while(rs.next()){
        String n = rs.getString("Name");
        String g = rs.getString("Genre");
        String an = rs.getString("Author_name");
        int code =rs.getInt("Book_code");
        mode.addRow(new Object[] {an,g,n,code});
        }
       rs.close();
       stmt.close();
       co.close();
            }
    catch(Exception e){JOptionPane.showMessageDialog(null,e);}
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f4ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
String name=f1.getText();
String author_name=f2.getText();
String genre=f3.getText();
String book_code=f4.getText();

try{
        Class.forName("java.sql.Driver");
       Connection co= DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
        java.sql.Statement stmt = co.createStatement();
        String q ="insert into books values('"+name+"','"+author_name+"','"+genre+"',"+book_code+")";
        stmt.executeUpdate(q);
       JOptionPane.showMessageDialog(null,"Data added successfully");
            }
    catch(Exception e){JOptionPane.showMessageDialog(null,e);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
String reader=tt3.getText();
String author_name=tt2.getText();
String contactno=tt4.getText();
String bookcode=tt1.getText();

try{
        Class.forName("java.sql.Driver");
       Connection co= DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
        java.sql.Statement stmt = co.createStatement();
        String q ="insert into issuedbooks values("+bookcode+",'"+author_name+"','"+reader+"',"+contactno+")";
        stmt.executeUpdate(q);
       JOptionPane.showMessageDialog(null,"Data added successfully");
            }
    catch(Exception e){JOptionPane.showMessageDialog(null,e);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JOptionPane.showMessageDialog(null,"logged-out successfull");
        well.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void tt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tt2ActionPerformed

    private void tt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tt3ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
DefaultTableModel mode =(DefaultTableModel) issuedbooks.getModel();   
int row=mode.getRowCount();
if(row>0){
    for(int i=0;i<row;i++)
    {mode.removeRow(0);}
    try{
        Class.forName("java.sql.Driver");
       Connection co= DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
        java.sql.Statement stmt = co.createStatement();
        String q ="select * from issuedbooks";
        ResultSet rs =stmt.executeQuery(q);
        while(rs.next()){
        int n = rs.getInt("Book_code");
        String g = rs.getString("Author");
        String an = rs.getString("Reader");
        int code =rs.getInt("contact_no");
        mode.addRow(new Object[] {n,g,an,code});
        }
       rs.close();
       stmt.close();
       co.close();
            }
    catch(Exception e){JOptionPane.showMessageDialog(null,e);}}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
int I = Integer.parseInt(ff1.getText());
try{
        Class.forName("java.sql.Driver");
       Connection co= DriverManager.getConnection("jdbc:mysql://localhost/librarymanagement","root","");
        java.sql.Statement stmt = co.createStatement();
        String q ="Delete from issuedbooks where Book_code="+I+"";
        stmt.executeUpdate(q);
       JOptionPane.showMessageDialog(null,"Data removed successfully");
            }
    catch(Exception e){JOptionPane.showMessageDialog(null,e);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        well.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
       JOptionPane.showMessageDialog(null,"YOU HAVE LOGGED OUT SUCCESSFULLY");
        well.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        well.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        well.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        adp1.setVisible(false);
        adp2.setVisible(false);
        adp3.setVisible(false);
        lbp1.setVisible(false);
        lbp2.setVisible(false);
        lbp3.setVisible(false);
        lbp4.setVisible(false);
        lbp5.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LIBRARIANS;
    private javax.swing.JPanel adp1;
    private javax.swing.JPanel adp2;
    private javax.swing.JPanel adp3;
    private javax.swing.JTable books;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField ff1;
    private javax.swing.JTable issuedbooks;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel lbp1;
    private javax.swing.JPanel lbp2;
    private javax.swing.JPanel lbp3;
    private javax.swing.JPanel lbp4;
    private javax.swing.JPanel lbp5;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JTextField pwd;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tt1;
    private javax.swing.JTextField tt2;
    private javax.swing.JTextField tt3;
    private javax.swing.JTextField tt4;
    private javax.swing.JPanel well;
    // End of variables declaration//GEN-END:variables
}
